Velke cisteni && kompletni zmena struktury && odstraneni zavislosti na nginx

diff --git a/debian/evok.postinst b/debian/evok.postinst
--- a/debian/evok.postinst
+++ b/debian/evok.postinst
@@ -5,82 +5,30 @@
 # Maintainer: martyy <triska@unipi.technology>
 
 
+
+case "$1" in
+	configure)
+	if [ -x /opt/unipi/tools/os-configurator ]; then
+    echo "Calling os-configurator update..." >&2
+    /opt/unipi/tools/os-configurator --force || echo "os-configurator return error, please call it manually."
+	fi
+
+  if [ -f /lib/systemd/system/owfs.service ]; then
+    echo "Restarting OWFS..." >&2
+    systemctl restart owfs || true
+  fi
+	;;
+
+	abort-upgrade|abort-remove|abort-deconfigure)
+	;;
+
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
+esac
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
-
 #DEBHELPER#
-
-
-# Source debconf library.
-. /usr/share/debconf/confmodule
-
-# ----------------------------------------------------------------------------------------
-# Issue 1 - Resolve nginx config files conflict - no more sites can share the same port 80
-# ----------------------------------------------------------------------------------------
-
-EVOK_NGINX_CONFILE="/etc/nginx/sites-available/evok"
-EVOK_NGINX_CONFILE_ENABLED="/etc/nginx/sites-enabled/evok"
-
-# Get conflict file(s) from the db filled during configuration operation
-db_get evok/nginx_conflict_files || true
-CONFLICT_CONFILE="$RET"
-
-if ! [ -z "$CONFLICT_CONFILE" ]; then # If a conflict has occurred
-
-    db_get evok/http_conflict || true
-
-    #echo "The selected way of solution $RET" >&2
-
-    case "$RET" in
-      *replace*) # Option 1 - Remove conflicting configuration file
-          echo "Removing conflict confile $CONFLICT_CONFILE" >&2
-          db_get evok/http_conflict_makesure || true
-
-          if [ -n "$DEBIAN_FRONTEND" -a "$DEBIAN_FRONTEND" = 'noninteractive' ]; then
-              RET=true
-          fi
-
-          if [ "$RET" = true ] ; then
-              rm "$CONFLICT_CONFILE"
-          fi
-          ;;
-      *another*) # Option 2 -Change port number in Evok's ngninx confile
-          db_get evok/control_website_port || true
-          #echo "Changing port to $RET - is it OK?" >&2
-          if [ -f "$EVOK_NGINX_CONFILE" ]; then
-              sed -i "s/listen[[:space:]]*[[:digit:]]*/listen $RET/g" "$EVOK_NGINX_CONFILE"
-          fi
-
-          if [ -f "$EVOK_NGINX_CONFILE_ENABLED" ]; then
-              sed -i "s/listen[[:space:]]*[[:digit:]]*/listen $RET/g" "$EVOK_NGINX_CONFILE_ENABLED"
-          fi
-
-          ;;
-      *) # Option 3 - Remove Evok Nginx confile
-         # All services provided by Nginx are disabled (incl. those proxy-ed) !!!
-          #echo "DO NOT USE EVOK WEBSITE" >&2
-          rm -f "$EVOK_NGINX_CONFILE_ENABLED"
-          rm -f "$EVOK_NGINX_CONFILE"
-          ;;
-    esac
-    #rm -f "/etc/nginx/sites-enabled/evok"
-fi
-
-# ----------------------------------------------------------------------------------------
-# FINALLY - Start the service
-# ----------------------------------------------------------------------------------------
-if [ -f /opt/unipi/tools/os-configurator ]; then
-  echo "Calling os-configurator update..." >&2
-  /opt/unipi/tools/os-configurator -u || echo "os-configurator return error, please call it manually."
-fi
-if [ -f /lib/systemd/system/owfs.service ]; then
-  echo "Restarting OWFS..." >&2
-  systemctl restart owfs || true
-fi
-systemctl start evok  || true
-echo "Starting Evok..." >&2
-systemctl start evok  || true
-echo "Restarting nginx..." >&2
-systemctl restart nginx || true
-
 exit 0
